module.exports = [
  { name: "Baga Beach", type: "beach", description: "Popular beach in Goa" },
  { name: "Palolem Beach", type: "beach", description: "Serene beach in South Goa" },
  { name: "Kovalem Beach", type: "beach", description: "Beautiful beach in Goa" },
  { name: "Juhu Beach", type: "beach", description: "Famous beach in Mumbai" },
  { name: "Marina Beach", type: "beach", description: "Longest beach in Chennai" },
  { name: "Mount Everest", type: "mountain", description: "World's highest mountain" },
  { name: "Kanchenjunga", type: "mountain", description: "Third highest mountain" },
  { name: "Nanda Devi", type: "mountain", description: "Second highest in India" },
  { name: "Anaimudi", type: "mountain", description: "Highest in Western Ghats" },
  { name: "Mullayanagiri", type: "mountain", description: "Highest peak in Karnataka" },
  { name: "Talakona Waterfall", type: "waterfall", description: "Highest in Andhra Pradesh" },
  { name: "Shivanasamudra", type: "waterfall", description: "Scenic waterfall" },
  { name: "Nohkalikai Waterfall", type: "waterfall", description: "Tallest plunge waterfall" },
  { name: "Dudhsagar Waterfall", type: "waterfall", description: "Four-tiered waterfall" },
  { name: "Jog Falls", type: "waterfall", description: "Second highest waterfall" },
  { name: "Tirupati Temple", type: "temple", description: "Famous Hindu temple" },
  { name: "Kashi Vishwanath", type: "temple", description: "Temple in Varanasi" },
  { name: "Jagannath Temple", type: "temple", description: "Temple in Puri" },
  { name: "Madurai Meenakshi", type: "temple", description: "Historic temple" },
  { name: "Vaishno Devi", type: "temple", description: "Temple in Jammu" },
  { name: "Nilgiri Hills", type: "cave", description: "Mountain range" },
  { name: "Satpura Range", type: "cave", description: "Hills in central India" },
  { name: "Aravalli Range", type: "cave", description: "Oldest mountain range" },
  { name: "Shillong Peak", type: "cave", description: "Highest in Meghalaya" },
  { name: "Vindhya Range", type: "cave", description: "Mountain range" }
];
